[package]
name = "ebalancer"
version = "0.1.0"
edition = "2021"
authors = ["Denis Kayshev <topenkoff@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ebalancer/ebalancer"

[dependencies]
